### ISSUE TITLE
Could not install and load arrow extension

### ISSUE THREAD

**Issue by yoonghm** [duckdb/arrow#20]
### The arrow integration is experimental. Support is currently only available on request.

- [X] I have permission to ask for support.

### What happens?

`arrow` extension is not available.

### To Reproduce

It seems that arrow extension is not available for DuckDB.

```
D install arrow;
Error: HTTP Error: Failed to download extension "arrow" at URL "http://extensions.duckdb.org/v0.9.1/windows_amd64/arrow.duckdb_extension.gz"
Extension "arrow" is an existing extension.
```

I manually tried using curl:

```bash
C:\MyLesson>curl http://extensions.duckdb.org/v0.9.1/windows_amd64/spatial.duckdb_extension.gz --output spatial.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.6M  100 19.6M    0     0  8546k      0  0:00:02  0:00:02 --:--:-- 8548k

C:\MyLesson>curl http://extensions.duckdb.org/v0.9.1/windows_amd64/arrow.duckdb_extension.gz --output arrow.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    301      0 --:--:-- --:--:-- --:--:--   301
```

The content of `arrow.gz`:

```TEXT
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>84AR33J34EXH1MG5</RequestId><HostId>X/otjtfkKUORQrBzUlUMgz4nhWs39YmqgRGNGrHHuQpK1xmZNBr5BJ3P6IXbY13BGOgm9FmmLDg=</HostId></Error>
```

### OS:

Windows 11

### Substrait-Extension Version:

NA

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Silvan-Fischer** [comment]
Facing same issue for an older version:
http://extensions.duckdb.org/v0.8.1/windows_amd64/arrow.duckdb_extension.gz

Noob question: Is there any way I can build the extention myself for my system? I use duckdb for node.js client.

**Comment by samansmink** [comment]
@Silvan-Fischer sure! just clone the repo and run `make` Note that you will need to enable unsigned extensions for this: https://duckdb.org/docs/extensions/overview.html#ensuring-the-integrity-of-extensions
